analysis: hh_bbtautau
type: nonresonant
model:
  parameters: [ kt ]
  param_dependent_bkg: true
  input_file_pattern: Run3_2022/bbtautau_mass/bbtautau_mass.root
hist_bins: [ 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0 ]
signalFractionForRelevantBins: 0.3
eras:
  - Run3_2022EE
channels:
  - tauTau/OS_Iso
categories:
  - res2b_inclusive
  - res1b_inclusive
  - boosted
processes:
  - process: data_obs
    is_data: true
    is_asimov_data: true
  - process: GluGlutoHHto2B2Tau
    hist_name: GluGlutoHHto2B2Tau_kl_1p00_kt_1p00_c2_0p00
    param_values: [ 1.0 ]
    is_signal: true
    scale: 2 * 6.272E-02 * 5.824E-01 * 34.13E-03
  - TT
  - DY
uncertainties:
  - name: lumi_13p6TeV
    type: lnN
    value: 0.014 # https://twiki.cern.ch/twiki/bin/view/CMS/LumiRecommendationsRun3
autolnNThr: 0.1
asymlnNThr: 0.001
ignorelnNThr: 0.001
autoMCStats:
  apply: true
  threshold: 20
  apply_to_signal: true
  mode: 1